### ISSUE TITLE
Can `required` field be expressed directly with OWL?

### ISSUE THREAD

**Issue by bbartley** [SD2E/opil#1]
Instead of using a custom `opil:required` property, can we use `owl:minCardinality` and `owl:maxCardinality` to define required fields?

**Comment by rmarkelo** [comment]
Yes, we could create a subclass of Parameter called RequiredParameter and state that instances of this class must have exactly one corresponding ParameterValue. But we still can't verify that the user has specified a value for a required parameter with OWL reasoning, that can only be checked with SHACL. So it's a matter of style. If we go with the RequiredParameter class, users of the ontology have to declare required parameters to be instances of both RequiredParameter and whatever Parameter subclass is appropriate to the data type. If we go with the opil:required property, then users have to set the property to true. I think that's somewhat simpler. Also, the opil:required property simplifies SHACL validation.

**Comment by bbartley** [comment]
Agree with @rmarkelo 's reasons here.  Closing.
