### ISSUE TITLE
Change OPIL root namespace

### ISSUE THREAD

**Issue by jakebeal** [SD2E/opil#104]
Since OPIL is intended to be a community standard, it should have a root namespace that isn't tied to BBN: `http://bbn.com/synbio/opil`

**Comment by jakebeal** [comment]
I snagged bioprotocols.org, which would allow us to use as a namespace `http://bioprotocols.org/opil/`
The other CPR languages can then have their own values instead of OPIL, e.g., `http://bioprotocols.org/paml/`

**Comment by bbartley** [comment]
Closed by #122
