### ISSUE TITLE
ProtocolInterface missing sample sets

### ISSUE THREAD

**Issue by jakebeal** [SD2E/opil#106]
ProtocolInterface is missing the hasSampleSet property, which should be cardinality 0..*

**Comment by bbartley** [comment]
Is the property synonymous with `allowedSamples`  in the powerpoint?  Which property name is preferable?

Also the powerpoint diagrams show one Toplevel class (`ProtocolInterface`) with another TopLevel as its child (`CombinatorialDerivation`).  This seems like an error in the spec.  From a more practical standpoint, it doesn't cause any _obvious_ bugs using pySBOL for file IO, but there may be more subtle bugs lurking.

**Comment by jakebeal** [comment]
I think `allowedSamples` would be better than `hasSampleSet`

And yes, the CDs should be references and not children.
