### ISSUE TITLE
Cardinalities on TimeInterval

### ISSUE THREAD

**Issue by jakebeal** [SD2E/opil#113]
In TimeInterval, both the minTime and maxTime cardinalities should be [0..1]

**Comment by bbartley** [comment]
This is strange.  I see the cardinality is 0..* in the UML diagram, but when I query the cardinality from the graph, it returns 0..1.  This may be a documentation error rather than an issue with the ontology itself

**Comment by bbartley** [comment]
Fixed in #113.
