### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by jakebeal** [SD2E/opil#14]
To allow use of OPIL in production software, we need its test files to be wrapped up for pytest and executed via continuous integration.

**Comment by bbartley** [comment]
CI is set up to run on push and PRs to master.

I tried to set up a CI badge in the README following the instructions here:
https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/adding-a-workflow-status-badge

But could not get it to work.  Will open a new issue for it.
