### ISSUE TITLE
Support Strateos to OPIL conversion to run outside of main method.

### ISSUE THREAD

**Issue by tramyn** [SD2E/opil#17]
I would like to call [generate_opil_from_strateos.py](https://github.com/SD2E/opil/blob/e33ce6c2cb333d590cea4a728feb80505df6c77e/opil/generate_opil_from_strateos.py#L14)
 in Intent Parser. However, looking at the current state of the converter, I do not want to send a json schema file to perform this conversion. It would be useful if opil has a function that allows IP to pass in a json object of the schema.

**Comment by bbartley** [comment]
I think you can pass a json object directly by calling `parse_strateos_json` method on a `StrateosOpilGenerator` instance.  

Does something like this work?
```
from generate_opil_from_strateos import StrateosOpilGenerator

opil_generator = StrateosOpilGenerator()
strateos_namespace = 'http://strateos.com/'
protocol_name = 'TimeSeriesHTC'
opil_generator.parse_strateos_json(strateos_namespace, protocol_name, protocol_json)
```

**Comment by tramyn** [comment]
@bbartley  I will need parse_strateos_json() from generate_opil_from_strateos.py to appear in the master branch. Could you make a pull request and merge this new change into master? I want to avoid IP from building off of OPIL branches that will potentially get deleted.

**Comment by bbartley** [comment]
@tramyn is the solution above working for you?  is there anything else we can do to make the converter interface more user-friendly or is this adequate for now?

**Comment by tramyn** [comment]
Converter interface works well! Thank you @bbartley . I'll file issues if I'm running into problems.
