### ISSUE TITLE
Stretos opil.ParameterValues does not have a valueOf property set

### ISSUE THREAD

**Issue by tramyn** [SD2E/opil#181]
The opil specification indicates that an opil.ParameterValue must have a valueOf set but when calling generate opil from Strateos protocol (ex: CellFreeRiboswitches). the valueOf is not set.

**Comment by bbartley** [comment]
I have a hunch that the offending `ParameterValues` are those that represent a `default_value` for a `Parameter`.  Can you provide a dotname for a `ParameterValue` that I can use to write a test case?
