### ISSUE TITLE
Support OPIL validator to run outside of main method

### ISSUE THREAD

**Issue by tramyn** [SD2E/opil#23]
I would like to call the OPIL validator but it's current implementation does not allow me to pass my opil objects to validate. I would like OPIL to have some validate function where I can pass an sbol document with opil objects for validating the document's content.

**Comment by rmarkelo** [comment]
Validation is done by importing validate from pyshacl. The validate method takes two graphs, one is the one you want to check and the other is the "shapes" graph. The pySBOL Document class now has a graph() method that will provide the first graph. The shapes graph can be created by parsing the shapes file. So this should be doable anywhere.
