### ISSUE TITLE
Is `hasValueObject` deprecated?

### ISSUE THREAD

**Issue by bbartley** [SD2E/opil#4]
The `ParameterValue` class defines a `hasValueObject` property, but it has no `rdfs:range` and therefore no specified data type.  Has the `hasValueObject` property been deprecated and replaced with `valueOf` property?

Related to the above, the `MeasureValue` appears to be the only one of six subclasses of `ParameterValue` (out of six total subclasses) that places a type restriction on the `hasValueObject` property.  If the property is not intended to be deprecated, then we need to specify type restrictions on the other subclasses as well.
```
opil:MeasureValue
  a owl:Class ;
  rdfs:label "Measure value" ;
  rdfs:subClassOf opil:ParameterValue ;
  rdfs:subClassOf [
      a owl:Restriction ;
      owl:allValuesFrom opil:MeasureParameter ;
      owl:onProperty opil:valueOf ;
    ] ;
  rdfs:subClassOf [
      a owl:Restriction ;
      owl:allValuesFrom om:Measure ;
      owl:onProperty opil:hasValueObject ;
    ] ;
```

**Comment by rmarkelo** [comment]
hasValueObject is intended to connect MeasureValue instances with om:Measure instances that hold their values (i.e. numerical values and units). The valueOf property connects ParameterValue instances to their corresponding Parameter instances. So they are different properties that serve different purposes. I am open to a less confusing nomenclature if you suggest one.

**Comment by rmarkelo** [comment]
The answer is, no, it is not deprecated, so I believe this should be closed
