### ISSUE TITLE
Support clone/copy methods for Parameter objects

### ISSUE THREAD

**Issue by tramyn** [SD2E/opil#50]
Intent Parser currently have clone methods supported for OPIL Parameter objects. These clone methods are used to avoid multiple users from overwriting the same Parameter objects when generating OPIL from an experiment request.  It would be useful if OPIL can have this type of method supported so Intent Parser does not have to ensure every field within a Parameter object have been correctly copied over to a new Parameter object.

**Comment by bbartley** [comment]
I believe the appropriate place to implement this is in pySBOL3 and have filed an issue there accordingly.
