### ISSUE TITLE
Provide alternative way to set default_value for a Parameter object

### ISSUE THREAD

**Issue by tramyn** [SD2E/opil#52]
Assigning a default_value to a Parameter is currently performed by doing the following:

```
param_field.default_value = [opil_value]
```

`param_field` in this case is an instance of a `Parameter` object and `opil_value` represents and instance of `ParameterValue` object. Unless a user knows that `opil_value` must be added to a list of size 1, it is unclear how it should be properly set. I would like to request a helper function that will allow a user to call and set a parameter value without knowing that it must be added into a list. Also, this will make it obvious to a user that a default value can only take one value and not a list with one value.

**Comment by bbartley** [comment]
Hi @tramyn I believe it is an error in opil that currently a list is required.  

Ideally, the correct usage should be, which I believe is more intuitive:
```
param_field.default_value = opil_value
```
This fix would be easy, but would potentially break compatibility with current release of IntentParser (but next release of IntentParser could be updated).  Would this fix be acceptable?

**Comment by bbartley** [comment]
Sorry, I guess I'm wrong about that.  The UML specification diagram shows that a `Parameter` can have multiple `defaultValues`.  Not sure why that is allowed.  @jakebeal can you comment?
