### ISSUE TITLE
Unexpected Parameter fields are added when converting Strateos ObstacleCourse Protocol

### ISSUE THREAD

**Issue by tramyn** [SD2E/opil#60]
Similar to #58, Intent Parser is picking on unexpected Parameter objects that does not correctly map to Strateos schema for ObstacleCourse Protocol. They are:

    "reagent_info.kill_switch.kill_switch",
    "reagent_info.kill_switch.kill_switch_final_conc.magnitude",
    "reagent_info.kill_switch.kill_switch_final_conc.unit",
    "reagent_info.inducer_info.inducer_1",
    "reagent_info.inducer_info.inducer_1_final_conc.magnitude",
    "reagent_info.inducer_info.inducer_1_final_conc.unit",
    "reagent_info.inducer_info.conditions.condition.day_1",
    "reagent_info.inducer_info.conditions.condition.day_1",
    "reagent_info.inducer_info.conditions.condition.day_2",
    "reagent_info.inducer_info.conditions.condition.day_1",
    "reagent_info.inducer_info.conditions.condition.day_2",
    "reagent_info.inducer_info.conditions.condition.day_3",
    "reagent_info.inducer_info.conditions.condition.day_1",
    "reagent_info.inducer_info.conditions.condition.day_2",
    "reagent_info.inducer_info.conditions.condition.day_3",
    "reagent_info.inducer_info.conditions.condition.day_4",
    "reagent_info.inducer_info.inducer_1",
    "reagent_info.inducer_info.inducer_1_final_conc.magnitude",
    "reagent_info.inducer_info.inducer_1_final_conc.unit",
    "reagent_info.inducer_info.inducer_2",
    "reagent_info.inducer_info.inducer_2_final_conc.magnitude",
    "reagent_info.inducer_info.inducer_2_final_conc.unit",
    "reagent_info.inducer_info.conditions.condition.day_1",
    "reagent_info.inducer_info.conditions.condition.day_1",
    "reagent_info.inducer_info.conditions.condition.day_2",
    "reagent_info.inducer_info.conditions.condition.day_1",
    "reagent_info.inducer_info.conditions.condition.day_2",
    "reagent_info.inducer_info.conditions.condition.day_3",
    "reagent_info.inducer_info.conditions.condition.day_1",
    "reagent_info.inducer_info.conditions.condition.day_2",
    "reagent_info.inducer_info.conditions.condition.day_3",
    "reagent_info.inducer_info.conditions.condition.day_4",
    "measurement_info.plate_reader_info.read_choice.excitation",
    "measurement_info.plate_reader_info.read_choice.emission",
    "measurement_info.plate_reader_info.read_choice.gain",
    "measurement_info.plate_reader_info.read_choice.integration_time",
    "measurement_info.flow_info.do_flow.flow_params",
    "measurement_info.flow_info.do_flow.flow_params"

**Comment by bbartley** [comment]
I think that this issue should be resolved... I believe that currently the parameters generated by the Strateos-to-OPIL converter do indeed map to json objects in the TimeSeries schema. @tramyn can you confirm whether you agree that this issue is resolved?

**Comment by tramyn** [comment]
@bbartley agreed!
