### ISSUE TITLE
Parameter default_value should be compositional

### ISSUE THREAD

**Issue by bbartley** [SD2E/opil#73]
Currently the `default_value` of a `Parameter` uses a URI to point to its respective `ParameterValue`.  However this `ParameterValue` is not composed with any `TopLevel` object, so it can't be added to an OPIL `Document`.  
(the sbol3 library forbids this and will throw an error if the user attempts to do it).  Consequently the association with the default `ParameterValue` is lost in serialization

**Comment by bbartley** [comment]
![OPIL_example_1](https://user-images.githubusercontent.com/2539464/104053537-7180d400-51b9-11eb-9504-0ab61002bb9e.png)

**Comment by jakebeal** [comment]
If I'm understanding correctly, the proposal is that, since ParameterValue is a child object for ExecutionRequest, it should also be a child object for Parameter?  If that's the proposal, then that seems entirely consistent, corrects a prior inconsistency, and I'm in favor.

**Comment by bbartley** [comment]
The proposal is that a ParameterValue should be a child object of Parameter, but only in the special case that it is a `default value`.

Normally a ParameterValue is associated with a parent ExperimentalRequest and its value is specified by the client.  In the case of the `default_value` property, the ParameterValue should be an intrinsic part of the ProtocolInterface and is provided by the lab.
